# Generated by Django 5.2.5 on 2025-08-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_categoriafaq_perguntafaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnae',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNAE'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_sede',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço da Sede'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='justificativa_indeferimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_funcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Função do Responsável'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVO', 'Ativo'), ('INDEFERIDO', 'Indeferido')], default='PENDENTE', max_length=10),
        ),
    ]
