# Generated by Django 5.2.5 on 2025-08-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_cnae_empresa_endereco_sede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código da subclasse CNAE, ex: 01.11-3/01', max_length=10, unique=True)),
                ('denominacao', models.CharField(help_text='Denominação da subclasse CNAE', max_length=255)),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
                'ordering': ['codigo'],
            },
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cnae',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnae_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_como_principal', to='empresas.cnae', verbose_name='CNAE Principal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnaes_secundarios',
            field=models.ManyToManyField(blank=True, related_name='empresas_como_secundario', to='empresas.cnae', verbose_name='CNAEs Secundários'),
        ),
    ]
