# Generated by Django 5.2.5 on 2025-08-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_cnae_remove_empresa_cnae_empresa_cnae_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCMCapítulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código do Capítulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='NCMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Código do Item (NCM 8 dígitos)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='NCMSeção',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código da Seção')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto_placeholder',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm_hs',
        ),
        migrations.AlterField(
            model_name='produto',
            name='certificacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='empresas.ncmitem', verbose_name='NCM do Produto'),
        ),
        migrations.CreateModel(
            name='NCMPosição',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código da Posição')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='empresas.ncmcapítulo')),
            ],
        ),
        migrations.AddField(
            model_name='ncmitem',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresas.ncmposição'),
        ),
        migrations.AddField(
            model_name='ncmcapítulo',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='empresas.ncmseção'),
        ),
    ]
